spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/tcm_recipes}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:pass1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:10}
      minimum-idle: ${DB_POOL_MIN_IDLE:2}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:20000}
      idle-timeout: ${DB_IDLE_TIMEOUT:300000}
      max-lifetime: ${DB_MAX_LIFETIME:1200000}
      leak-detection-threshold: ${DB_LEAK_DETECTION:60000}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:false}
        open-in-view: false
    show-sql: ${JPA_SHOW_SQL:false}
  flyway:
    enabled: ${FLYWAY_ENABLED:false}

logging:
  level:
    root: INFO
    com.tcm.backend: DEBUG

publisher:
  storage:
    local-directory: build/datasets
  min-app-version: 1.0.0

# Application Security Configuration
app:
  jwt:
    secret: ${JWT_SECRET:development-super-secret-key-that-must-be-at-least-32-characters-long-for-local-dev}  # No default - must be provided
    access-token-expiration-minutes: ${JWT_ACCESS_EXPIRY_MINUTES:15}
    refresh-token-expiration-days: ${JWT_REFRESH_EXPIRY_DAYS:7}
    issuer: ${JWT_ISSUER:tcm-app-backend}
  password:
    min-length: ${PASSWORD_MIN_LENGTH:12}
    require-uppercase: ${PASSWORD_REQUIRE_UPPERCASE:true}
    require-lowercase: ${PASSWORD_REQUIRE_LOWERCASE:true}
    require-digits: ${PASSWORD_REQUIRE_DIGITS:true}
    require-special-chars: ${PASSWORD_REQUIRE_SPECIAL_CHARS:true}
    expiration-days: ${PASSWORD_EXPIRATION_DAYS:90}
    min-entropy: ${PASSWORD_MIN_ENTROPY:50}
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://app.tcmapp.com,https://tcmapp.com}
    rate-limit:
      auth-requests-per-hour: ${RATE_LIMIT_AUTH_REQUESTS:100}
      guest-requests-per-hour: ${RATE_LIMIT_GUEST_REQUESTS:100}
      authenticated-requests-per-hour: ${RATE_LIMIT_AUTH_USER_REQUESTS:1000}
    cookie:
      secure: ${COOKIE_SECURE:false}  # Set to true in production
      same-site: ${COOKIE_SAME_SITE:strict}
    lockout:
      duration-minutes: ${ACCOUNT_LOCKOUT_DURATION:30}

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health,info,metrics}
  endpoint:
    health:
      show-details: ${ACTUATOR_HEALTH_DETAILS:when-authorized}
