spring:
  datasource:
    url: jdbc:h2:mem:tcm_recipes;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
    open-in-view: false
    show-sql: true
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: INFO
    com.tcm.backend: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE